"""core.collection_registry — DAFTAR RESMI koleksi MongoDB yang boleh dipakai.

KENAPA BERKAS INI ADA (F0.1, 2026-08-12)
----------------------------------------
Forensik `scripts/_forensic_ssot_v3.py` mengukur: **386 koleksi** disebut kode
sementara hanya **192** ada di database, **13** ditulis-tak-pernah-dibaca,
**28** dibaca-tak-pernah-ditulis, dan **156** hanya disentuh SATU berkas.
Itu wujud teknis dari keluhan owner: *"fitur yang berdiri sendiri, lupa
hubungannya dengan api lain"* dan *"collection yang di panggil miss semua"*.

Mekanisme pencegahnya sederhana: **koleksi baru harus didaftarkan di sini**.
`scripts/gate_marketing_ssot.py` memeriksa seluruh `backend/routes|core|services`
dan MERAH bila ada koleksi yang tidak terdaftar — jadi menambah koleksi diam-diam
tidak lagi mungkin, dan setiap koleksi punya pemilik domain yang jelas.

Cara menambah koleksi baru (WAJIB, urutannya tidak boleh dibalik):
  1. tulis kontrak fieldnya di `memory/SSOT_KONTRAK_DATA_2026-08-12.md`;
  2. daftarkan namanya di `REGISTRY` di bawah beserta domainnya;
  3. baru tulis kodenya.
"""
from __future__ import annotations

# nama koleksi → domain pemilik
REGISTRY: dict[str, str] = {
    "acc_purchase_requests": "finance",
    "acc_valuation_report_runs": "finance",
    "accessory_shipment_items": "lain",
    "accessory_shipments": "lain",
    "activity_logs": "lain",
    "ai_business_summaries": "lain",
    "ai_config": "lain",
    "ai_rca_history": "lain",
    "ai_response_cache": "lain",
    "announcements": "lain",
    "approval_chains": "lain",
    "approval_requests": "lain",
    "assistant_chat_history": "lain",
    "attachments": "lain",
    "bank_recon_sessions": "lain",
    "bank_recon_txns": "lain",
    "buyer_shipment_items": "penjualan",
    "buyer_shipments": "penjualan",
    "buyer_short_records": "penjualan",
    "buyers": "lain",
    "capacity_config": "lain",
    "client_login_attempts": "lain",
    "cmt_receipt_lines": "lain",
    "cmt_receipts": "lain",
    "cmt_short_shipments": "lain",
    "comm_channels": "lain",
    "comm_conversations": "lain",
    "comm_messages": "lain",
    "comm_read_receipts": "lain",
    "company_settings": "lain",
    "counters": "lain",
    "cutting_orders": "lain",
    "cutting_progress": "lain",
    "da_asset_assignments": "lain",
    "da_assets": "lain",
    "da_kpi_badges": "lain",
    "da_kpi_goals": "lain",
    "da_kpi_perform": "lain",
    "da_kpi_periods": "lain",
    "da_kpi_questions": "lain",
    "da_kpi_results": "lain",
    "da_kpi_submissions": "lain",
    "da_payroll_allowances": "lain",
    "dewi_accessory_requests": "lain",
    "dewi_ai_actions": "lain",
    "dewi_asset_assignments": "lain",
    "dewi_asset_categories": "lain",
    "dewi_asset_depreciation": "lain",
    "dewi_asset_disposal_requests": "lain",
    "dewi_asset_loans": "lain",
    "dewi_asset_maintenance": "lain",
    "dewi_asset_pm_acknowledgments": "lain",
    "dewi_asset_scans": "lain",
    "dewi_asset_transfers": "lain",
    "dewi_assets": "lain",
    "dewi_client_users": "lain",
    "dewi_cmt_component_requests": "produksi",
    "dewi_cmt_deliveries": "produksi",
    "dewi_cmt_delivery_orders": "produksi",
    "dewi_cmt_jobs": "produksi",
    "dewi_cmt_partners": "produksi",
    "dewi_cmt_payments": "produksi",
    "dewi_cmt_permak": "produksi",
    "dewi_cmt_progress": "produksi",
    "dewi_cmt_progress_reports": "produksi",
    "dewi_cutting_batches": "lain",
    "dewi_cutting_requests": "lain",
    "dewi_delivery_orders": "lain",
    "dewi_hpp_snapshots_maklon": "lain",
    "dewi_hpp_snapshots_po": "lain",
    "dewi_kasbon_requests": "lain",
    "dewi_kreator_requests": "lain",
    "dewi_lms_attempts": "hr",
    "dewi_lms_courses": "hr",
    "dewi_lms_enrollments": "hr",
    "dewi_lms_materials": "hr",
    "dewi_lms_progress": "hr",
    "dewi_lms_quizzes": "hr",
    "dewi_lms_submissions": "hr",
    "dewi_maklon_advance_payments": "maklon",
    "dewi_maklon_bom": "maklon",
    "dewi_maklon_bom_templates": "maklon",
    "dewi_maklon_buyer_catalog": "maklon",
    "dewi_maklon_clients": "maklon",
    "dewi_maklon_credit_notes": "maklon",
    "dewi_maklon_dispatches": "maklon",
    "dewi_maklon_hpp": "maklon",
    "dewi_maklon_inventory": "maklon",
    "dewi_maklon_invoices": "maklon",
    "dewi_maklon_material_issues": "maklon",
    "dewi_maklon_material_receive": "maklon",
    "dewi_maklon_payments": "maklon",
    "dewi_maklon_pos": "maklon",
    "dewi_maklon_qc_checks": "maklon",
    "dewi_maklon_sample_revisions": "maklon",
    "dewi_maklon_samples": "maklon",
    "dewi_material_issues": "lain",
    "dewi_mgmt_alert_config": "lain",
    "dewi_onboarding_checklists": "lain",
    "dewi_onboarding_templates": "lain",
    "dewi_org_positions": "lain",
    "dewi_org_units": "lain",
    "dewi_perf_assignments": "lain",
    "dewi_perf_cycles": "lain",
    "dewi_perf_kpis": "lain",
    "dewi_perf_reviews": "lain",
    "dewi_procurement_requests": "lain",
    "dewi_provider_config": "lain",
    "dewi_recruitment_candidates": "lain",
    "dewi_recruitment_jobs": "lain",
    "dewi_rnd_hpp": "rnd",
    "dewi_rnd_materials": "rnd",
    "dewi_rnd_patterns": "rnd",
    "dewi_rnd_revisions": "rnd",
    "dewi_rnd_sample_costing": "rnd",
    "dewi_rnd_sample_requests": "rnd",
    "dewi_rnd_styles": "rnd",
    "dewi_rnd_tech_packs": "rnd",
    "dewi_rnd_variants": "rnd",
    "dewi_scheduler_runs": "lain",
    "dewi_system_config": "lain",
    "dewi_toko_flashsales": "lain",
    "dewi_toko_orders": "lain",
    "dewi_toko_pack_batches": "lain",
    "dewi_toko_products": "lain",
    "dewi_toko_returns": "lain",
    "dewi_toko_reviews": "lain",
    "dewi_universal_scans": "lain",
    "doc_number_configs": "lain",
    "document_number_configs": "lain",
    "employee_documents": "lain",
    "employee_expense_categories": "lain",
    "employee_expense_gl_mappings": "lain",
    "employee_per_diem_rates": "lain",
    "employee_travel_requests": "lain",
    "employee_travel_settlements": "lain",
    "fx_rates": "lain",
    "fx_revaluation_runs": "lain",
    "garments": "lain",
    "hr_ai_results": "lain",
    "hr_issued_documents": "lain",
    "hr_shift_assignments": "lain",
    "hris_assignments": "hr",
    "hris_cycles": "hr",
    "hris_kpi_assignments": "hr",
    "hris_reviews": "hr",
    "hris_training_completions": "hr",
    "invoice_adjustments": "lain",
    "invoice_change_history": "lain",
    "invoice_edit_requests": "lain",
    "invoices": "lain",
    "login_attempts": "lain",
    "marketing_ab_experiments": "marketing",
    "marketing_account_health": "marketing",
    "marketing_account_targets": "marketing",
    "marketing_ads_data": "marketing",
    "marketing_ai_content_history": "marketing",
    "marketing_alert_runs": "marketing",
    "marketing_alert_settings": "marketing",
    "marketing_budgets": "marketing",
    "marketing_catalog_items": "marketing",
    "marketing_catalogs": "marketing",
    "marketing_churn_scores": "marketing",
    "marketing_complaints": "marketing",
    "marketing_content_calendar": "marketing",
    "marketing_creator_catalog": "marketing",
    "marketing_creator_item_requests": "marketing",
    "marketing_creator_sessions": "marketing",
    "marketing_creator_targets": "marketing",
    "marketing_data_import_sessions": "marketing",
    # F1 (2026-08-12) — ingatan susunan kolom ekspor: (source_type, fingerprint)
    # → pemetaan yang sudah dikonfirmasi manusia, supaya impor rutin tidak perlu
    # memetakan ulang dan tidak pernah menebak diam-diam.
    "marketing_data_import_formats": "marketing",
    # F3 (2026-08-14) — jejak PEMULIHAN impor `update_only` (Ekspor B/C).
    # Satu dokumen per pesanan yang diubah: nilai field sebelum diubah, status
    # sebelum diubah, dan `items[]` sebelum diubah (kalau retur per SKU ikut).
    # Dibaca HANYA oleh `POST /sessions/{id}/rollback`; tidak pernah dijumlah,
    # tidak pernah jadi sumber angka laporan.
    "marketing_data_import_undo": "marketing",
    "marketing_discounts": "marketing",
    "marketing_dynamic_pricing_events": "marketing",
    "marketing_dynamic_pricing_settings": "marketing",
    "marketing_dynamic_pricing_suggestions": "marketing",
    "marketing_integration_settings": "marketing",
    "marketing_kol_campaigns": "marketing",
    "marketing_kol_creators": "marketing",
    "marketing_kol_login_attempts": "marketing",
    "marketing_live_session_products": "marketing",
    "marketing_live_sessions": "marketing",
    "marketing_livehost_scripts": "marketing",
    "marketing_livehost_shifts": "marketing",
    "marketing_livehost_training": "marketing",
    "marketing_livehost_training_progress": "marketing",
    "marketing_livehosts": "marketing",
    "marketing_orders": "marketing",
    "marketing_platform_accounts": "marketing",
    "marketing_product_launches": "marketing",
    "marketing_returns": "marketing",
    "marketing_reviews": "marketing",
    "marketing_sales_data": "marketing",
    "marketing_samples": "marketing",
    "marketing_spend_entries": "marketing",
    "marketing_stock_syncs": "marketing",
    "marketing_task_templates": "marketing",
    "marketing_tasks": "marketing",
    "marketing_webhook_events": "marketing",
    "material_defect_reports": "lain",
    "material_request_items": "lain",
    "material_requests": "lain",
    "notif_category_config": "lain",
    "notif_user_prefs": "lain",
    "notifications": "lain",
    "payments": "lain",
    "payroll_automation_config": "lain",
    "payroll_automation_log": "lain",
    "payroll_entries": "lain",
    "payroll_runs": "lain",
    "payslips": "lain",
    "pdf_document_settings": "lain",
    "pdf_export_configs": "lain",
    "peer_feedbacks": "lain",
    "permissions": "lain",
    "po_accessories": "pengadaan",
    "po_items": "pengadaan",
    "portal_calendar_events": "lain",
    "portal_notes": "lain",
    "portal_quick_links": "lain",
    "portal_reminders": "lain",
    "portal_todos": "lain",
    "product_variants": "lain",
    "production_job_items": "produksi",
    "production_jobs": "produksi",
    "production_material_returns": "produksi",
    "production_pos": "produksi",
    "production_progress": "produksi",
    "production_return_items": "produksi",
    "production_returns": "produksi",
    "production_variances": "produksi",
    "products": "lain",
    "push_subscriptions": "lain",
    "rahaza_360_cycles": "lain",
    "rahaza_accruals": "lain",
    "rahaza_ai_audit_logs": "lain",
    "rahaza_ai_chat_history": "lain",
    "rahaza_ai_usage_logs": "lain",
    "rahaza_alert_settings": "lain",
    "rahaza_alerts": "lain",
    "rahaza_ap_invoices": "finance",
    "rahaza_ap_payments": "finance",
    "rahaza_approval_delegations": "finance",
    "rahaza_ar_invoices": "finance",
    "rahaza_ar_payments": "finance",
    "rahaza_attendance": "hr",
    "rahaza_attendance_events": "hr",
    "rahaza_audit_logs": "lain",
    "rahaza_bank_recon_adjustments": "lain",
    "rahaza_bank_transfers": "lain",
    "rahaza_boms": "lain",
    "rahaza_budget_items": "lain",
    "rahaza_budgets": "lain",
    "rahaza_bundles": "lain",
    "rahaza_career_chats": "lain",
    "rahaza_career_reports": "lain",
    "rahaza_cash_accounts": "lain",
    "rahaza_cash_movements": "lain",
    "rahaza_channel_gl_mapping": "lain",
    "rahaza_coa_accounts": "finance",
    "rahaza_coa_auto_settings": "finance",
    "rahaza_colors": "lain",
    "rahaza_cost_centers": "lain",
    "rahaza_costing_settings": "lain",
    "rahaza_credit_notes": "lain",
    "rahaza_customers": "lain",
    "rahaza_defect_codes": "lain",
    "rahaza_depr_schedules": "lain",
    "rahaza_downtime_events": "lain",
    "rahaza_employee_loan_repayments": "hr",
    "rahaza_employee_loans": "hr",
    "rahaza_employees": "hr",
    "rahaza_expense_claims": "lain",
    "rahaza_expenses": "lain",
    "rahaza_fg_inventory": "lain",
    "rahaza_fg_issues": "lain",
    "rahaza_fg_matrix": "lain",
    "rahaza_fg_movements": "lain",
    "rahaza_fg_reservations": "lain",
    "rahaza_fixed_assets": "lain",
    "rahaza_grn_inspections": "lain",
    "rahaza_handover_templates": "lain",
    "rahaza_hpp_snapshots": "lain",
    "rahaza_integration_settings": "lain",
    "rahaza_job_applications": "lain",
    "rahaza_job_postings": "lain",
    "rahaza_journal_entries": "finance",
    "rahaza_journal_lines": "finance",
    "rahaza_leave_balances": "hr",
    "rahaza_leave_requests": "hr",
    "rahaza_leave_types": "hr",
    "rahaza_line_assignments": "lain",
    "rahaza_lines": "lain",
    "rahaza_locations": "lain",
    "rahaza_machine_downtime": "lain",
    "rahaza_machines": "lain",
    "rahaza_maintenance_logs": "lain",
    "rahaza_maintenance_predictions": "lain",
    "rahaza_maklon_quotes": "lain",
    "rahaza_material_categories": "inventory",
    "rahaza_material_cost_history": "inventory",
    "rahaza_material_issues": "inventory",
    "rahaza_material_movements": "inventory",
    "rahaza_material_reservations": "inventory",
    "rahaza_material_stock": "inventory",
    "rahaza_materials": "inventory",
    "rahaza_model_process_sop": "lain",
    "rahaza_model_variants": "lain",
    "rahaza_models": "lain",
    "rahaza_office_locations": "lain",
    "rahaza_okr_key_results": "lain",
    "rahaza_okr_objectives": "lain",
    "rahaza_orders": "lain",
    "rahaza_overtime_requests": "lain",
    "rahaza_payroll_profiles": "hr",
    "rahaza_payroll_runs": "hr",
    "rahaza_payroll_settings": "hr",
    "rahaza_payslips": "hr",
    "rahaza_periods": "lain",
    "rahaza_petty_cash_funds": "lain",
    "rahaza_petty_cash_txns": "lain",
    "rahaza_posting_profiles": "lain",
    "rahaza_processes": "lain",
    "rahaza_product_categories": "lain",
    "rahaza_production_calendar": "lain",
    "rahaza_purchase_orders": "lain",
    "rahaza_qc_events": "lain",
    "rahaza_racks": "lain",
    "rahaza_salary_adjustments": "lain",
    "rahaza_salary_grades": "lain",
    "rahaza_schedules": "lain",
    "rahaza_setup_state": "lain",
    "rahaza_shift_handovers": "lain",
    "rahaza_shift_templates": "lain",
    "rahaza_shifts": "lain",
    "rahaza_shipments": "lain",
    "rahaza_sizes": "lain",
    "rahaza_skill_analyses": "lain",
    "rahaza_skill_requirements": "lain",
    "rahaza_stock_ledger": "inventory",
    "rahaza_styles": "lain",
    "rahaza_supplier_price_lists": "lain",
    "rahaza_suppliers": "lain",
    "rahaza_webauthn_challenges": "lain",
    "rahaza_webauthn_credentials": "lain",
    "rahaza_wip_events": "lain",
    "rahaza_work_orders": "lain",
    "rahaza_zkteco_devices": "lain",
    "rate_limit_buckets": "lain",
    "reminders": "lain",
    "role_permissions": "lain",
    "roles": "lain",
    "study_groups": "lain",
    "users": "lain",
    "vendor_jobs": "vendor",
    "vendor_material_inspection_items": "vendor",
    "vendor_material_inspections": "vendor",
    "vendor_partners": "vendor",
    "vendor_progress_reports": "vendor",
    "vendor_shipment_items": "vendor",
    "vendor_shipments": "vendor",
    "warehouse_receiving": "lain",
    "wh_buildings": "gudang",
    "wh_cmt_dispatches": "gudang",
    "wh_delivery_notes": "gudang",
    "wh_fabric_roll_movements": "gudang",
    "wh_fabric_rolls": "gudang",
    "wh_location_migration_map": "gudang",
    "wh_opname3_counts": "gudang",
    "wh_opname3_sessions": "gudang",
    "wh_opname_sessions2": "gudang",
    "wh_pending_movements": "gudang",
    "wh_picklists": "gudang",
    "wh_placement_movements": "gudang",
    "wh_positions": "gudang",
    "wh_quarantine_items": "gudang",
    "wh_rack_alerts": "gudang",
    "wh_racks": "gudang",
    "wh_rca_audit": "gudang",
    "wh_returns": "gudang",
    "wh_stock_schema_reconcile_log": "gudang",
    "wh_unit_conversions": "gudang",
    "wh_unit_master": "gudang",
    "wh_zones": "gudang",
    "wms_fabric_rolls": "gudang",
    "work_orders": "lain",
    "workspace_documents": "lain",
    "workspace_shares": "lain",
    "workspace_versions": "lain",
}

# Koleksi yang DIHAPUS di F0.6 (mesin impor lama) atau tujuan yang SALAH.
# Menyentuhnya dari kode = gate MERAH; pengganti yang benar ada di nilai dict.
DEPRECATED: dict[str, str] = {
    "marketing_import_sessions":     "marketing_data_import_sessions",
    "marketing_import_uploads":      "marketing_data_import_sessions",
    "marketing_import_templates":    "marketing_data_import_formats",
    "marketing_import_history":      "marketing_data_import_sessions",
    "marketing_discount_campaigns":  "marketing_discounts",
    "marketing_sample_shipments":    "marketing_samples",
}

# Koleksi BARU yang sudah disetujui rencana F0–F10 tetapi belum ditulis kodenya.
# Didaftarkan lebih dulu supaya gate tidak menghalangi saat fasenya dikerjakan.
PLANNED: dict[str, str] = {
    "marketing_settlements":            "marketing",   # F9 — pencairan marketplace
    "marketing_period_locks":           "marketing",   # F5/F6 — kunci periode
    "marketing_change_log":             "marketing",   # F6 — jejak nilai lama
    "marketing_data_import_formats":    "marketing",   # F1 — sidik format impor
    # F7.2 (2026-08-13) — KPI harian dari ekspor Seller Center (statistik toko,
    # Live/Video). SENGAJA dipisah dari `marketing_sales_data`: definisi angkanya
    # milik platform (pesanan dibuat/siap dikirim/dibayar) dan tidak boleh
    # dijumlah dengan omzet pesanan. Kontrak field: lihat
    # memory/SSOT_KONTRAK_DATA_2026-08-12.md §KPI PLATFORM.
    "marketing_platform_kpi_daily":     "marketing",
}


def all_allowed() -> set[str]:
    return set(REGISTRY) | set(PLANNED)


def is_registered(name: str) -> bool:
    return name in REGISTRY or name in PLANNED


def assert_registered(name: str) -> None:
    """Dipakai helper akses DB dinamis. Melempar ValueError yang menjelaskan langkahnya."""
    if name in DEPRECATED:
        raise ValueError(
            f"Koleksi '{name}' SUDAH DIHAPUS (F0.6). Pakai '{DEPRECATED[name]}'.")
    if not is_registered(name):
        raise ValueError(
            f"Koleksi '{name}' tidak terdaftar. Tulis kontraknya di "
            f"memory/SSOT_KONTRAK_DATA_2026-08-12.md, daftarkan di "
            f"core/collection_registry.py, baru pakai di kode.")


def domain_of(name: str) -> str:
    return REGISTRY.get(name) or PLANNED.get(name) or "tidak-terdaftar"
